### PR TITLE
Rocket reservation feature

### PR DESCRIPTION
**Pull request by zamcham**
- Add rocket reservation feature
- keeps track of reserved rockets on the profile component

### CODE REVIEW

**Review by christianonoh — CHANGES_REQUESTED** [review]
Hi @zamcham,

I've been reviewing your code for the new rocket reservation system, and I wanted to let you know that I think you've done a great job. The code is well-written, easy to understand, and it's clear that you've put a lot of thought into the user experience.

During my review, I did come across one minor issue that I believe requires your attention. It seems that the reserved rockets are getting discarded if a user attempts to reserve another rocket after switching to a different route. I've captured a video demonstrating this bug for your reference. Please find the attached video file [here](https://www.loom.com/share/e9abfc9a09934305958ab55c21bcf81b).

Other than that, I think the code is great. Thanks for your hard work!

**Comment by zamcham** [comment]
@christianonoh please take a look now and let me know

**Comment by zamcham** [comment]
@christianonoh the issue with the reservation has been fixed, you can take a look now

**Review by christianonoh — APPROVED** [review]
## Great work! @zamcham, you can now merge the branch.

**Pull request merged**
